cflags = [
    '-Wall',
    '-g',
    '-pthread',
]  

if GetOption('debug_build'):
    cflags.append('-O0')
else:
    cflags.append('-O2')
    cflags.append('-DNDEBUG')

env=Environment(CC = 'gcc',
    CCFLAGS = ' '.join(cflags)
) 

epoll_helloworld = env.Program('../../bin/gbtcp-epoll-helloworld', 'main.c')
