cflags = [
    '-Wall',
    '-g',
    '-pthread',
]  

if GetOption('debug_build'):
    cflags.append('-O0')
    suffix = "-d"
else:
    cflags.append('-O2')
    cflags.append('-DNDEBUG')
    suffix=""

env=Environment(CC = 'gcc',
    CCFLAGS = ' '.join(cflags)
) 

env.Program('../../bin/epoll-helloworld%s' % suffix, 'bench_epoll.c')
